export const leaderBoardData = {
    Chess: [
        { player: "Arceus", score: 2180 },
        { player: "Void", score: 2055 },
        { player: "Purple", score: 1980 },
        { player: "Knight", score: 1925 },
        { player: "Bishop", score: 1870 },
        { player: "Rook", score: 1810 },
        { player: "PawnMaster", score: 1765 },
        { player: "Checkmate", score: 1700 },
        { player: "GrandFox", score: 1650 },
        { player: "SilentMove", score: 1590 },
    ],

    Valorant: [
        { player: "AceHunter", score: 920 },
        { player: "Pixel", score: 880 },
        { player: "Shadow", score: 850 },
        { player: "Nova", score: 820 },
        { player: "Viper", score: 790 },
        { player: "Ghost", score: 760 },
        { player: "Phoenix", score: 735 },
        { player: "Cypher", score: 700 },
        { player: "Reyna", score: 680 },
        { player: "JettMain", score: 650 },
    ],

    "Counter-Strike 2": [
        { player: "Headshot", score: 22150 },
        { player: "SniperKing", score: 21400 },
        { player: "ClutchGod", score: 20850 },
        { player: "FlashBang", score: 20120 },
        { player: "Smoke", score: 19500 },
        { player: "RushB", score: 18950 },
        { player: "AWPMaster", score: 18200 },
        { player: "FragMachine", score: 17650 },
        { player: "Terror", score: 17000 },
        { player: "Defuser", score: 16500 },
    ],

    PUBG: [
        { player: "ChickenDinner", score: 5200 },
        { player: "Survivor", score: 5050 },
        { player: "DropZone", score: 4920 },
        { player: "Conqueror", score: 4810 },
        { player: "AcePlayer", score: 4680 },
        { player: "Sniper", score: 4550 },
        { player: "Parachute", score: 4420 },
        { player: "LootGoblin", score: 4310 },
        { player: "RushKing", score: 4180 },
        { player: "FinalCircle", score: 4050 },
    ],

    Tetris: [
        { player: "BlockMaster", score: 3420 },
        { player: "LineClear", score: 3300 },
        { player: "Tetromino", score: 3180 },
        { player: "Stacker", score: 3050 },
        { player: "FastDrop", score: 2920 },
        { player: "PuzzleKing", score: 2800 },
        { player: "Rotate", score: 2690 },
        { player: "HardDrop", score: 2550 },
        { player: "Combo", score: 2410 },
        { player: "ClearLine", score: 2280 },
    ],

    "Clash of Clans": [
        { player: "Chief", score: 6120 },
        { player: "WarLord", score: 5980 },
        { player: "DragonRider", score: 5850 },
        { player: "TownHall16", score: 5720 },
        { player: "Barbarian", score: 5600 },
        { player: "ArcherQueen", score: 5480 },
        { player: "GrandWarden", score: 5350 },
        { player: "ElectroDragon", score: 5210 },
        { player: "GoblinKing", score: 5080 },
        { player: "Miner", score: 4950 },
    ],
};
